package com.fulton_shaw.example;

//AUTO GENERATED BY velocity-templatee
//   Template    = Pojo.java.vm
//   Argument    = template Pojo.java.vm ADD_AUTOGEN=true AUTHOR=xiaohuadong CLASS_NAME=com.fulton_shaw.example.Pojo EXTEND_NAME= VERSION=3.0.0 'FIELD_LIST=Long id,String name,String uuid'
//   JVM Options:
//      file.resource.loader.path  = D:\Pool\Projects\wobstorm\through-layers\flavors\idea-plugin\githubs\velocity-templatee\src\main\resources
//      import.class.list          = 
//      input.encoding             = 
//      output.encoding            = 

/**
* @author xiaohuadong
* @date 2019/6/9
* @since 3.0.0
*/
public class Pojo {
    private Long id;
    private String name;
    private String uuid;

    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public String getName(){
        return this.name;
    }

    public void setName(String name){
        this.name = name;
    }

    public String getUuid(){
        return this.uuid;
    }

    public void setUuid(String uuid){
        this.uuid = uuid;
    }


    public String toString(){
        StringBuilder s = new StringBuilder();
        s.append("Pojo{");
        s.append("id = ").append(this.id);
        s.append(", name = ").append(this.name);
        s.append(", uuid = ").append(this.uuid);
        s.append("}");
        return s.toString();
    }

    public static void main(String[] args) {
        Pojo pojo =new Pojo();
        pojo.setName("Pojo");
        System.out.println(pojo);
    }

}
